title: Brian Amaral # your name (or website title) here
logo: "/images/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a bit-brusher, passionate about data and solving complicated problems! 
  <br><br>
  Data Engineer. Working in the tech industry for the last 2.5 years, working with SQL, Spark, DBT, Airbyte, Airflow, Redshift and Athena. Experienced in building ELT/ETL, Data Quality, Data Warehousing, Data Lake Design and Data Architecture. Enjoy working in the full data lifecycle, from ingestion to serving. Designing scalable designs. Let me help you with your Modern Data Stack!
  <br><br>
  <a href="https://www.linkedin.com/in/brian-amaral/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
